### ISSUE TITLE
Profil + Portfolio Navigation

### ISSUE THREAD

**Issue by fraaalk** [fraaalk/reflect#1]
In der Navigation (Header + Footer) wird Profil gelistet mit Unterpunkten. In den Layouts ist keine der Seiten zu finden. Alle Punkte werden auf der Homepage beschrieben. Sind das nur Anker? Oder kommen noch die fehlenden Unterseiten?

**Comment by thedanielhanke** [comment]
nunzt bekannte elemente, keine neuen!
wie die karteikarten "typische loesungen" wie bei den fargeseiten.
