### ISSUE TITLE
Go-Struktur

### ISSUE THREAD

**Issue by thedanielhanke** [fraaalk/reflect#9]
- [x] Bei hover bitte gesamte Go aufklappen
- [x] Innere Waabe (diese miniding) klickbar machen
- [x] Innere Waabe mit Text versehen (oben: "Balancierte", unten: "Fuehrung") (lass telen)

**Comment by fraaalk** [comment]
ist klickbar (aktuell mit # verlinkt) auf hover nur alles zeigen oder alles aufklappen? also hover = klick?
